name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            # The last 3 LTS releases
            java: [ 11, 17, 21 ]
    name: Java ${{matrix.java}}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
      - name: Build with Maven
        run: mvn -B package    
      - uses: actions/upload-artifact@v4
        with:
          name: build${{matrix.java}}
          path: .
